// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/generate": {
            "get": {
                "description": "Generate Passwoed",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Password"
                ],
                "summary": "Generates Passwords",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Length of the password",
                        "name": "length",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Number of digits (Default: Length/4)",
                        "name": "digits",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of symbols (Default: Length/4)",
                        "name": "symbols",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Allow repeated chars (Default: true)",
                        "name": "allow_repeat",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd.PasswordResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cmd.PasswordError"
                        }
                    }
                }
            }
        },
        "/validate": {
            "get": {
                "description": "Validates Passwoed",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Password"
                ],
                "summary": "Validates Passwords",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The password to validate",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd.ValidationResponse"
                        }
                    },
                    "499": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/cmd.ValidationResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "cmd.PasswordError": {
            "type": "object",
            "properties": {
                "allow_repeat": {
                    "type": "boolean"
                },
                "digits": {
                    "type": "integer"
                },
                "error": {
                    "type": "string"
                },
                "length": {
                    "type": "integer"
                },
                "symbols": {
                    "type": "integer"
                }
            }
        },
        "cmd.PasswordResponse": {
            "type": "object",
            "properties": {
                "allow_repeat": {
                    "type": "boolean"
                },
                "digits": {
                    "type": "integer"
                },
                "generated_in_ns": {
                    "type": "integer"
                },
                "length": {
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                },
                "sha_256_sum": {
                    "type": "string"
                },
                "sha_512_sum": {
                    "type": "string"
                },
                "symbols": {
                    "type": "integer"
                }
            }
        },
        "cmd.ValidationResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "validates": {
                    "type": "boolean"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "Password Generator API",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
